### ISSUE TITLE
Add Amazon S3

### ISSUE THREAD

**Issue by kellybell** [betahex/cdncomparison#12]

**Comment by luboskmetko** [comment]
Amazon S3 is not a CDN, afaik, they will serve all your files from US, no matter where your users are. (We were offloading images on one our WP site to S3 and they were served from US servers and very slow for me in Europe).

So you will need a CDN like their CloudFront or some other, if you use S3.

**Comment by kellybell** [comment]
Well it's funny you should say that, bc CloudFlare isn't a CDN either(!).
As I just discovered bc I had to move all my clients files to S3. It turns
out that _CloudFlare doesn't host the files at all_! They just cache them
all over the world and serve them. But you STILL have to host them
somewhere else, no matter how expensive or inefficient that turns out to
be.

So to me it makes _exactly_ as much sense to call S3 a CDN as it does to
call CloudFlare one... That's why I want them _both_ in the comparison, so
these kinds of differences can be uncovered. As a developer, this shit
matters, and is like it all to be a lot more transparent.

Thanks,

Kelly Bell
Founder and CTO
Gotham City Drupal
917.446.1555

On Feb 5, 2016, at 02:36, Lubos Kmetko notifications@github.com wrote:

Amazon S3 is not a CDN, afaik, they will serve all your files from US, no
matter where your users are. (We were offloading images on one our WP site
to S3 and they were served from US servers and very slow for me in Europe).

So you will need a CDN like their CloudFront or some other, if you use S3.

**Comment by luboskmetko** [comment]
I was talking about Amazon's CloudFront - https://aws.amazon.com/cloudfront/, but I see your point. The table could include info about whether CDN supports hosting files directly, eg. like https://client.cdn77.com/support/knowledgebase/general-faq/what-is-a-cdn-storage

**Comment by kellybell** [comment]
Oh sorry - yes I misread. I'm familiar with cloudfront. But yeah - is love
to see another column in your table for "hosts files" etc.

Thanks

Kelly Bell
Founder and CTO
Gotham City Drupal
917.446.1555

On Feb 5, 2016, at 03:46, Lubos Kmetko notifications@github.com wrote:

I was talking about Amazon's CloudFront - https://aws.amazon.com/cloudfront/,
but I see your point. The table could include info about whether CDN
supports hosting files directly, eg. like
https://client.cdn77.com/support/knowledgebase/general-faq/what-is-a-cdn-storage

**Comment by betahex** [comment]
rejected: s3 is not a CDN
