### ISSUE TITLE
A row for "Flexible SSL" support

### ISSUE THREAD

**Issue by ithinkihaveacat** [betahex/cdncomparison#14]
I'm not sure this is an industry-wide term, but Flexible SSL, as defined [by CloudFlare](https://www.cloudflare.com/ssl/), refers to the situation where: "there is an encrypted connection between your site visitors and CloudFlare, but not from CloudFlare to your server." (That is, the connection between the CDN and the user is encrypted, but the connection between the CDN and the origin is not.)

**Comment by matthewgall** [comment]
Generally, this feature is known as SSL termination.

**Disclaimer:** I work for CloudFlare

**Comment by betahex** [comment]
This is something most CDNs can do.
