### ISSUE TITLE
CDN77 minimum pricing

### ISSUE THREAD

**Issue by matthewselby** [betahex/cdncomparison#25]
looks like CDN77 has a minimum startup fee of $149 after 14-day free trial. These credits expire after one year unless you "recharge" your account with another minimum of $150 which then extends your funds another year...how lame, they looked pretty great. "confirmed this with support"
<img width="960" alt="screen shot 2016-06-13 at 4 22 31 pm" src="https://cloud.githubusercontent.com/assets/14359078/16026436/77836972-3183-11e6-9e35-649b7bd01b6d.png">

**Comment by betahex** [comment]
fixed
