### ISSUE TITLE
Add information about Brotli support?

### ISSUE THREAD

**Issue by KenjiBaheux** [betahex/cdncomparison#26]
Hi,

I'm Kenji Baheux working on the web platform in the Chrome team.

[Brotli](http://google-opensource.blogspot.de/2015/09/introducing-brotli-new-compression.html) is a new compression algorithm, which is now available in Chrome and Firefox as a content-encoding option for HTTPS. It offers significant compression wins over gzip (e.g. 25% better compression being typical).

Sam Saffron (at Discourse), in his [Brotli overview article](https://samsaffron.com/archive/2016/06/15/the-current-state-of-brotli-compression), suggested that it would be quite useful to have information about Brotli support on cdncomparison.com

It's currently supported by the following CDNs:
- KeyCDN
- CDN77 ("appears to be letting Brotli through")

Also, we are aware of a few on-going efforts for other CDNs.
For reference, here are some deployment examples we are aware of: Facebook, Google Fonts.

Would it be possible to add information about Brotli to cdncomparison.com?
Best,

**Comment by betahex** [comment]
fixed
