### ISSUE TITLE
Add G-core CDN 

### ISSUE THREAD

**Issue by Anastasia-isk** [betahex/cdncomparison#37]
Please add G-core CDN  to the comparison list. 
Detailed information about service and logo in attachment.
Website: https://gcdn.co
[G-CDN - company profile.xlsx](https://github.com/betahex/cdncomparison/files/732075/G-CDN.-.company.profile.xlsx)
[G-CDN - company profile.pdf](https://github.com/betahex/cdncomparison/files/732076/G-CDN.-.company.profile.pdf)
![g-cdn](https://cloud.githubusercontent.com/assets/25363448/22328695/9b925a28-e3ce-11e6-935b-fe3f1f7563db.png)

**Comment by betahex** [comment]
rejected: insignificant relevance
