### ISSUE TITLE
Compare purge features: purge-by-tag, wildcard-support in purge-by-url

### ISSUE THREAD

**Issue by sebknzl** [betahex/cdncomparison#45]
Hi,

thanks for the page, it's very informative.

I think it would be interesting to evaluate CDNs for the mentioned features.

Purge-by-tag is if you can purge assets by a tag, which the origin server has sent along, e.g. with the "Cache-Tag" header.

Not all CDNs support wildcards in their purge-by-url feature.

Purge-by-tag: KeyCDN, (Cloudflare)
Wildcard-support: Azure, Fastly
 
Thanks

**Comment by betahex** [comment]
Added in 85f3c5f.
