### ISSUE TITLE
Show which CDNs offer extra CORS support

### ISSUE THREAD

**Issue by aaemnnosttv** [betahex/cdncomparison#47]
It would be nice to list which CDNs offer extra support for adding CORS headers for certain resources.

E.g.
- KeyCDN [CORS](https://www.keycdn.com/blog/cors-cdn/)
- MaxCDN [CORS Headers](https://www.maxcdn.com/features/rules/)

**Comment by betahex** [comment]
Added in commit 85f3c5f.
