### ISSUE TITLE
Please consider adding the following CDN providers

### ISSUE THREAD

**Issue by amavarick** [betahex/cdncomparison#48]
I love what you have done here.  Seems like one of the few "comparison" sites that are easy to follow in chart form while fairly comprehensive.

Please consider adding the following CDN providers:
https://cdnsun.com/
https://www.cdn77.com

I see you have closed a few other requests out stating pull request required.  Is it your requirement that the requester research the answers and submit a pull request on cdncomparison/index.html with the requested changes?

Thank you so much for your time...

**Comment by betahex** [comment]
I might add them if I remove another provider from the list.
