### ISSUE TITLE
KeyCDN has IPV6

### ISSUE THREAD

**Issue by tovare** [betahex/cdncomparison#51]
Hi,
The comparison has a question mark for IPV6 with keyCDN.

When i do nslookup on one of my zones on KeyCDN I get an IPV6 address.

e.g. nslookup video-56b4.kxcdn.com  , example file: https://video-56b4.kxcdn.com/out.mp4

**Comment by betahex** [comment]
This doesn't seem to be true. I'll check it again later this year.

**Comment by tovare** [comment]
You´re right. Sorry about that. I checked again, and there´s no response on IPV6. Don´t know why I thought so in February.
