### ISSUE TITLE
KeyCDN doesn't really support Origin Push

### ISSUE THREAD

**Issue by themenow** [betahex/cdncomparison#54]
They offer Push Zone at an extra cost, you can upload files to their storage cluster, but files are not distributed to edge servers until be requested (pull).

> Although your content has been uploaded to  the storage cluster, data is only deployed to an edge server location if it has been requested.

https://www.keycdn.com/support/upload-data-to-a-push-zone/

**Comment by betahex** [comment]
matter of definition: origin push means not hosted on the own server
