### ISSUE TITLE
Add Cloudflare

### ISSUE THREAD

**Issue by mitcheal** [betahex/cdncomparison#7]
I don't see Cloudflare listed unless their CDN goes by another name, by all indications on their site they developed their own CDN.

**Comment by pencoyd** [comment]
CloudFlare operates its own hardware, software, and network, so yes, our CDN is ours alone. (Not the only benefit, but that's one of them.)

**Comment by justincavery** [comment]
This was one that came immediately to mind as missing, be great to add it!

**Comment by quest** [comment]
+1

**Comment by betahex** [comment]
cloudflare needs different approach to compare (pricing, limits e.g. not caching all file types)
